//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionInitParameters) DeepCopyInto(out *ConditionInitParameters) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionInitParameters.
func (in *ConditionInitParameters) DeepCopy() *ConditionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionObservation) DeepCopyInto(out *ConditionObservation) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionObservation.
func (in *ConditionObservation) DeepCopy() *ConditionObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionParameters) DeepCopyInto(out *ConditionParameters) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionParameters.
func (in *ConditionParameters) DeepCopy() *ConditionParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsInitParameters) DeepCopyInto(out *ConditionsInitParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]ConditionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsInitParameters.
func (in *ConditionsInitParameters) DeepCopy() *ConditionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsObservation) DeepCopyInto(out *ConditionsObservation) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]ConditionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsObservation.
func (in *ConditionsObservation) DeepCopy() *ConditionsObservation {
	if in == nil {
		return nil
	}
	out := new(ConditionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsParameters) DeepCopyInto(out *ConditionsParameters) {
	*out = *in
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = make([]ConditionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsParameters.
func (in *ConditionsParameters) DeepCopy() *ConditionsParameters {
	if in == nil {
		return nil
	}
	out := new(ConditionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionFilterInitParameters) DeepCopyInto(out *DimensionFilterInitParameters) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionFilterInitParameters.
func (in *DimensionFilterInitParameters) DeepCopy() *DimensionFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(DimensionFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionFilterObservation) DeepCopyInto(out *DimensionFilterObservation) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionFilterObservation.
func (in *DimensionFilterObservation) DeepCopy() *DimensionFilterObservation {
	if in == nil {
		return nil
	}
	out := new(DimensionFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionFilterParameters) DeepCopyInto(out *DimensionFilterParameters) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make([]FilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionFilterParameters.
func (in *DimensionFilterParameters) DeepCopy() *DimensionFilterParameters {
	if in == nil {
		return nil
	}
	out := new(DimensionFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityFilterInitParameters) DeepCopyInto(out *EntityFilterInitParameters) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityFilterInitParameters.
func (in *EntityFilterInitParameters) DeepCopy() *EntityFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(EntityFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityFilterObservation) DeepCopyInto(out *EntityFilterObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityFilterObservation.
func (in *EntityFilterObservation) DeepCopy() *EntityFilterObservation {
	if in == nil {
		return nil
	}
	out := new(EntityFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityFilterParameters) DeepCopyInto(out *EntityFilterParameters) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityFilterParameters.
func (in *EntityFilterParameters) DeepCopy() *EntityFilterParameters {
	if in == nil {
		return nil
	}
	out := new(EntityFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTemplateInitParameters) DeepCopyInto(out *EventTemplateInitParameters) {
	*out = *in
	if in.DavisMerge != nil {
		in, out := &in.DavisMerge, &out.DavisMerge
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EventType != nil {
		in, out := &in.EventType, &out.EventType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTemplateInitParameters.
func (in *EventTemplateInitParameters) DeepCopy() *EventTemplateInitParameters {
	if in == nil {
		return nil
	}
	out := new(EventTemplateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTemplateObservation) DeepCopyInto(out *EventTemplateObservation) {
	*out = *in
	if in.DavisMerge != nil {
		in, out := &in.DavisMerge, &out.DavisMerge
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EventType != nil {
		in, out := &in.EventType, &out.EventType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTemplateObservation.
func (in *EventTemplateObservation) DeepCopy() *EventTemplateObservation {
	if in == nil {
		return nil
	}
	out := new(EventTemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTemplateParameters) DeepCopyInto(out *EventTemplateParameters) {
	*out = *in
	if in.DavisMerge != nil {
		in, out := &in.DavisMerge, &out.DavisMerge
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EventType != nil {
		in, out := &in.EventType, &out.EventType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make([]MetadataParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTemplateParameters.
func (in *EventTemplateParameters) DeepCopy() *EventTemplateParameters {
	if in == nil {
		return nil
	}
	out := new(EventTemplateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Events) DeepCopyInto(out *Events) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Events.
func (in *Events) DeepCopy() *Events {
	if in == nil {
		return nil
	}
	out := new(Events)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Events) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsInitParameters) DeepCopyInto(out *EventsInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventEntityDimensionKey != nil {
		in, out := &in.EventEntityDimensionKey, &out.EventEntityDimensionKey
		*out = new(string)
		**out = **in
	}
	if in.EventTemplate != nil {
		in, out := &in.EventTemplate, &out.EventTemplate
		*out = make([]EventTemplateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LegacyID != nil {
		in, out := &in.LegacyID, &out.LegacyID
		*out = new(string)
		**out = **in
	}
	if in.ModelProperties != nil {
		in, out := &in.ModelProperties, &out.ModelProperties
		*out = make([]ModelPropertiesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryDefinition != nil {
		in, out := &in.QueryDefinition, &out.QueryDefinition
		*out = make([]QueryDefinitionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsInitParameters.
func (in *EventsInitParameters) DeepCopy() *EventsInitParameters {
	if in == nil {
		return nil
	}
	out := new(EventsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsList) DeepCopyInto(out *EventsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Events, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsList.
func (in *EventsList) DeepCopy() *EventsList {
	if in == nil {
		return nil
	}
	out := new(EventsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EventsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsObservation) DeepCopyInto(out *EventsObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventEntityDimensionKey != nil {
		in, out := &in.EventEntityDimensionKey, &out.EventEntityDimensionKey
		*out = new(string)
		**out = **in
	}
	if in.EventTemplate != nil {
		in, out := &in.EventTemplate, &out.EventTemplate
		*out = make([]EventTemplateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LegacyID != nil {
		in, out := &in.LegacyID, &out.LegacyID
		*out = new(string)
		**out = **in
	}
	if in.ModelProperties != nil {
		in, out := &in.ModelProperties, &out.ModelProperties
		*out = make([]ModelPropertiesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryDefinition != nil {
		in, out := &in.QueryDefinition, &out.QueryDefinition
		*out = make([]QueryDefinitionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsObservation.
func (in *EventsObservation) DeepCopy() *EventsObservation {
	if in == nil {
		return nil
	}
	out := new(EventsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsParameters) DeepCopyInto(out *EventsParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventEntityDimensionKey != nil {
		in, out := &in.EventEntityDimensionKey, &out.EventEntityDimensionKey
		*out = new(string)
		**out = **in
	}
	if in.EventTemplate != nil {
		in, out := &in.EventTemplate, &out.EventTemplate
		*out = make([]EventTemplateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LegacyID != nil {
		in, out := &in.LegacyID, &out.LegacyID
		*out = new(string)
		**out = **in
	}
	if in.ModelProperties != nil {
		in, out := &in.ModelProperties, &out.ModelProperties
		*out = make([]ModelPropertiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryDefinition != nil {
		in, out := &in.QueryDefinition, &out.QueryDefinition
		*out = make([]QueryDefinitionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsParameters.
func (in *EventsParameters) DeepCopy() *EventsParameters {
	if in == nil {
		return nil
	}
	out := new(EventsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsSpec) DeepCopyInto(out *EventsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsSpec.
func (in *EventsSpec) DeepCopy() *EventsSpec {
	if in == nil {
		return nil
	}
	out := new(EventsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventsStatus) DeepCopyInto(out *EventsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventsStatus.
func (in *EventsStatus) DeepCopy() *EventsStatus {
	if in == nil {
		return nil
	}
	out := new(EventsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterInitParameters) DeepCopyInto(out *FilterInitParameters) {
	*out = *in
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
	if in.DimensionValue != nil {
		in, out := &in.DimensionValue, &out.DimensionValue
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterInitParameters.
func (in *FilterInitParameters) DeepCopy() *FilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(FilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterObservation) DeepCopyInto(out *FilterObservation) {
	*out = *in
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
	if in.DimensionValue != nil {
		in, out := &in.DimensionValue, &out.DimensionValue
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterObservation.
func (in *FilterObservation) DeepCopy() *FilterObservation {
	if in == nil {
		return nil
	}
	out := new(FilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterParameters) DeepCopyInto(out *FilterParameters) {
	*out = *in
	if in.DimensionKey != nil {
		in, out := &in.DimensionKey, &out.DimensionKey
		*out = new(string)
		**out = **in
	}
	if in.DimensionValue != nil {
		in, out := &in.DimensionValue, &out.DimensionValue
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterParameters.
func (in *FilterParameters) DeepCopy() *FilterParameters {
	if in == nil {
		return nil
	}
	out := new(FilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataInitParameters) DeepCopyInto(out *MetadataInitParameters) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(string)
		**out = **in
	}
	if in.MetadataValue != nil {
		in, out := &in.MetadataValue, &out.MetadataValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataInitParameters.
func (in *MetadataInitParameters) DeepCopy() *MetadataInitParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataObservation) DeepCopyInto(out *MetadataObservation) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(string)
		**out = **in
	}
	if in.MetadataValue != nil {
		in, out := &in.MetadataValue, &out.MetadataValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataObservation.
func (in *MetadataObservation) DeepCopy() *MetadataObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataParameters) DeepCopyInto(out *MetadataParameters) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(string)
		**out = **in
	}
	if in.MetadataValue != nil {
		in, out := &in.MetadataValue, &out.MetadataValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataParameters.
func (in *MetadataParameters) DeepCopy() *MetadataParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPropertiesInitParameters) DeepCopyInto(out *ModelPropertiesInitParameters) {
	*out = *in
	if in.AlertCondition != nil {
		in, out := &in.AlertCondition, &out.AlertCondition
		*out = new(string)
		**out = **in
	}
	if in.AlertOnNoData != nil {
		in, out := &in.AlertOnNoData, &out.AlertOnNoData
		*out = new(bool)
		**out = **in
	}
	if in.DealertingSamples != nil {
		in, out := &in.DealertingSamples, &out.DealertingSamples
		*out = new(float64)
		**out = **in
	}
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = new(float64)
		**out = **in
	}
	if in.SignalFluctuation != nil {
		in, out := &in.SignalFluctuation, &out.SignalFluctuation
		*out = new(float64)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ViolatingSamples != nil {
		in, out := &in.ViolatingSamples, &out.ViolatingSamples
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPropertiesInitParameters.
func (in *ModelPropertiesInitParameters) DeepCopy() *ModelPropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModelPropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPropertiesObservation) DeepCopyInto(out *ModelPropertiesObservation) {
	*out = *in
	if in.AlertCondition != nil {
		in, out := &in.AlertCondition, &out.AlertCondition
		*out = new(string)
		**out = **in
	}
	if in.AlertOnNoData != nil {
		in, out := &in.AlertOnNoData, &out.AlertOnNoData
		*out = new(bool)
		**out = **in
	}
	if in.DealertingSamples != nil {
		in, out := &in.DealertingSamples, &out.DealertingSamples
		*out = new(float64)
		**out = **in
	}
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = new(float64)
		**out = **in
	}
	if in.SignalFluctuation != nil {
		in, out := &in.SignalFluctuation, &out.SignalFluctuation
		*out = new(float64)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ViolatingSamples != nil {
		in, out := &in.ViolatingSamples, &out.ViolatingSamples
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPropertiesObservation.
func (in *ModelPropertiesObservation) DeepCopy() *ModelPropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(ModelPropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPropertiesParameters) DeepCopyInto(out *ModelPropertiesParameters) {
	*out = *in
	if in.AlertCondition != nil {
		in, out := &in.AlertCondition, &out.AlertCondition
		*out = new(string)
		**out = **in
	}
	if in.AlertOnNoData != nil {
		in, out := &in.AlertOnNoData, &out.AlertOnNoData
		*out = new(bool)
		**out = **in
	}
	if in.DealertingSamples != nil {
		in, out := &in.DealertingSamples, &out.DealertingSamples
		*out = new(float64)
		**out = **in
	}
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = new(float64)
		**out = **in
	}
	if in.SignalFluctuation != nil {
		in, out := &in.SignalFluctuation, &out.SignalFluctuation
		*out = new(float64)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ViolatingSamples != nil {
		in, out := &in.ViolatingSamples, &out.ViolatingSamples
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPropertiesParameters.
func (in *ModelPropertiesParameters) DeepCopy() *ModelPropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(ModelPropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryDefinitionInitParameters) DeepCopyInto(out *QueryDefinitionInitParameters) {
	*out = *in
	if in.Aggregation != nil {
		in, out := &in.Aggregation, &out.Aggregation
		*out = new(string)
		**out = **in
	}
	if in.DimensionFilter != nil {
		in, out := &in.DimensionFilter, &out.DimensionFilter
		*out = make([]DimensionFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EntityFilter != nil {
		in, out := &in.EntityFilter, &out.EntityFilter
		*out = make([]EntityFilterInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagementZone != nil {
		in, out := &in.ManagementZone, &out.ManagementZone
		*out = new(string)
		**out = **in
	}
	if in.MetricKey != nil {
		in, out := &in.MetricKey, &out.MetricKey
		*out = new(string)
		**out = **in
	}
	if in.MetricSelector != nil {
		in, out := &in.MetricSelector, &out.MetricSelector
		*out = new(string)
		**out = **in
	}
	if in.QueryOffset != nil {
		in, out := &in.QueryOffset, &out.QueryOffset
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryDefinitionInitParameters.
func (in *QueryDefinitionInitParameters) DeepCopy() *QueryDefinitionInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueryDefinitionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryDefinitionObservation) DeepCopyInto(out *QueryDefinitionObservation) {
	*out = *in
	if in.Aggregation != nil {
		in, out := &in.Aggregation, &out.Aggregation
		*out = new(string)
		**out = **in
	}
	if in.DimensionFilter != nil {
		in, out := &in.DimensionFilter, &out.DimensionFilter
		*out = make([]DimensionFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EntityFilter != nil {
		in, out := &in.EntityFilter, &out.EntityFilter
		*out = make([]EntityFilterObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagementZone != nil {
		in, out := &in.ManagementZone, &out.ManagementZone
		*out = new(string)
		**out = **in
	}
	if in.MetricKey != nil {
		in, out := &in.MetricKey, &out.MetricKey
		*out = new(string)
		**out = **in
	}
	if in.MetricSelector != nil {
		in, out := &in.MetricSelector, &out.MetricSelector
		*out = new(string)
		**out = **in
	}
	if in.QueryOffset != nil {
		in, out := &in.QueryOffset, &out.QueryOffset
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryDefinitionObservation.
func (in *QueryDefinitionObservation) DeepCopy() *QueryDefinitionObservation {
	if in == nil {
		return nil
	}
	out := new(QueryDefinitionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryDefinitionParameters) DeepCopyInto(out *QueryDefinitionParameters) {
	*out = *in
	if in.Aggregation != nil {
		in, out := &in.Aggregation, &out.Aggregation
		*out = new(string)
		**out = **in
	}
	if in.DimensionFilter != nil {
		in, out := &in.DimensionFilter, &out.DimensionFilter
		*out = make([]DimensionFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EntityFilter != nil {
		in, out := &in.EntityFilter, &out.EntityFilter
		*out = make([]EntityFilterParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagementZone != nil {
		in, out := &in.ManagementZone, &out.ManagementZone
		*out = new(string)
		**out = **in
	}
	if in.MetricKey != nil {
		in, out := &in.MetricKey, &out.MetricKey
		*out = new(string)
		**out = **in
	}
	if in.MetricSelector != nil {
		in, out := &in.MetricSelector, &out.MetricSelector
		*out = new(string)
		**out = **in
	}
	if in.QueryOffset != nil {
		in, out := &in.QueryOffset, &out.QueryOffset
		*out = new(float64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryDefinitionParameters.
func (in *QueryDefinitionParameters) DeepCopy() *QueryDefinitionParameters {
	if in == nil {
		return nil
	}
	out := new(QueryDefinitionParameters)
	in.DeepCopyInto(out)
	return out
}
