apiVersion: event.crossplane.io/v1alpha1
kind: Events
metadata:
  annotations:
    meta.upbound.io/example-id: event/v1alpha1/events
  labels:
    testing.upbound.io/example-name: '#name#'
  name: '#name#'
spec:
  forProvider:
    enabled: true
    eventEntityDimensionKey: dt.entity.host
    eventTemplate:
    - davisMerge: false
      description: some description
      eventType: CUSTOM_ALERT
      title: sample_name
    modelProperties:
    - alertCondition: ABOVE
      alertOnNoData: false
      dealertingSamples: 5
      samples: 5
      threshold: 1
      type: STATIC_THRESHOLD
      violatingSamples: 3
    queryDefinition:
    - aggregation: AVG
      dimensionFilter:
      - filter:
        - dimensionKey: dt.entity.host
          dimensionValue: HOST-9DDF1200A29EFAC9
        - dimensionKey: dt.entity.disk.name
          dimensionValue: /local
        - dimensionKey: dt.entity.disk
          dimensionValue: DISK-3DC3FC42FBB07595
      entityFilter:
      - conditions:
        - condition:
          - operator: EQUALS
            type: NAME
            value: HOST-80FF882B3215BF1A
          - operator: EQUALS
            type: ENTITY_ID
            value: HOST-32D0DB4904B28FB3
          - operator: EQUALS
            type: MANAGEMENT_ZONE
            value: "-189204438944455158"
          - operator: EQUALS
            type: HOST_GROUP_NAME
            value: HOST-42FDD00356069724
        dimensionKey: dt.entity.host
      metricKey: builtin:host.disk.usedPct
      type: METRIC_KEY
    summary: sample_name
